# Generated by Django 5.2.5 on 2025-08-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='subjects',
            field=models.ManyToManyField(related_name='classrooms', to='school_diary.subject'),
        ),
    ]
