# Generated by Django 5.2.5 on 2025-08-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_diary', '0004_alter_grade_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='date',
            field=models.DateField(),
        ),
    ]
