# Generated by Django 5.2.5 on 2025-09-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_diary', '0005_alter_grade_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('H', 'H'), ('NA', '—')], max_length=2, null=True),
        ),
    ]
