# Generated by Django 5.2.5 on 2025-08-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_alter_profile_user_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Адмін'), ('manager', 'Менеджер'), ('user', 'Користувач')], default='user', max_length=20),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
