# Generated by Django 5.2.5 on 2025-08-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_like_created_at_alter_like_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['thread', 'created_at']},
        ),
        migrations.RemoveField(
            model_name='thread',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
    ]
