# Generated by Django 5.2.5 on 2025-09-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_announcement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
