# Generated by Django 5.2.5 on 2025-09-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_delete_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='tag',
            field=models.CharField(blank=True, choices=[('folowing', 'Following'), ('introduction', 'Introduction'), ('feedback', 'Feedback')], max_length=20, null=True),
        ),
    ]
