# Generated by Django 5.2.5 on 2025-09-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Текст'), ('radio', 'Один варіант'), ('checkbox', 'Кілька варіантів')], default='text', max_length=10),
        ),
    ]
